browser:
  browserName: chrome #firefox
  webElementTimeOut: 25  #Explicitly wait
  webBrowserImplicitTimeOut: 10



environment:
  intEnv:
    appUrl: https://demo.aspnetawesome.com/
    env_name: intEnv
    firstName: Donatello
    meal1: Banana
    meal2: Potato
    meal3: Mango
    expectedMessage: dinner created
    active: false

  testEnv:
    appUrl: https://demo.aspnetawesome.com/
    env_name: testEnv
    firstName: Leonardo
    meal1: Apple
    meal2: Onion
    meal3: Papaya
    expectedMessage: dinner created
    active: true

  defaultEnv:
    appUrl: https://demo.aspnetawesome.com/
    env_name: defaultEnv
    firstName: Jack
    meal1: Cucumber
    meal2: Potato
    meal3: Apple
    expectedMessage: dinner created
    active: false