environment:
  intEnv:
    appUrl: https://demo.aspnetawesome.com/
    env_name: intEnv
    firstName: Albert
    meal1: Banana
    meal2: Potato
    meal3: Mango
    expectedMessage: Form send with success
    active: true

  testEnv:
    appUrl: https://demo.aspnetawesome.com/
    env_name: testEnv
    firstName: Leonardo
    meal1: Apple
    meal2: Onion
    meal3: Papaya
    expectedMessage: Form send with success
    active: false

  defaultEnv:
    appUrl: https://demo.aspnetawesome.com/
    env_name: defaultEnv
    firstName: Jack
    meal1: Cucumber
    meal2: Potato
    meal3: Apple
    expectedMessage: Form send with success
    active: false